server:
  port: 8810

spring:
  application:
    name: upload-file-center

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
#  redis:
#    host: 127.0.0.1
#    port: 6379

#datasource
#spring.datasource.url=jdbc:mysql://localhost:3306/database?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
#spring.datasource.username=username
#spring.datasource.password=password
#
##mybatis
#mybatis.mapper-locations=classpath:mapper/*.xml

#log level
#logging.level.root=info
#logging.config=classpath:logback-spring.xml

#上传设置。运行于虚拟机中，默认将文件上传至本地目录，local.url为虚拟机中nginx代理的path
# 实际保存的路径为
upload:
  enable: local
  local:
    path: /app/dev/upload-file-center/articles/
    url: http://192.168.223.128:88/articles/
  qiniu:
    url: rbm8degyo.hn-bkt.clouddn.com
    path:

